<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rbtinyshop"
 *
 * Auto generated by Extension Builder 2014-08-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TinyShop',
	'description' => 'Shop Extension für TYPO3 auf Basis von Extbase und Fluid.',
	'category' => 'plugin',
	'author' => 'Ronny Baumann',
	'author_email' => 'ronnybaumann80@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);